# Generated by Django 3.1.2 on 2020-11-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
