# Generated by Django 3.1.2 on 2020-12-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Nico', max_length=30, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='S', max_length=30, verbose_name='last_name'),
            preserve_default=False,
        ),
    ]
